# Generated by Django 5.2.8 on 2025-12-11 20:30

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('image', models.ImageField(help_text='Main recipe photo', upload_to=shop.models.recipe_image_path)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('prep_time', models.PositiveIntegerField(default=15, help_text='In minutes')),
                ('cook_time', models.PositiveIntegerField(default=30, help_text='In minutes')),
                ('servings', models.PositiveIntegerField(default=4)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured_products', models.ManyToManyField(blank=True, related_name='featured_in_recipes', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, help_text='e.g. 500g, 2 cups, 1 bunch', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'unique_together': {('recipe', 'product')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='used_in_recipes', through='shop.RecipeIngredient', to='shop.product'),
        ),
    ]
