# Generated by Django 5.2.8 on 2025-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_zone', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('items', models.JSONField()),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('pdf_invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
