# Generated by Django 5.2.8 on 2025-11-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
